CREATE TABLE [dbo].[Module]
(
  [ModuleId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  [ModuleName] VARCHAR(100) NOT NULL UNIQUE,
  [Created] DATETIME NOT NULL,
  [Updated] DATETIME NOT NULL,
  [UserCreated] UNIQUEIDENTIFIER NOT NULL,
  [UserUpdated] UNIQUEIDENTIFIER NOT NULL,
  [IsActive] BIT NOT NULL DEFAULT 1,
  CONSTRAINT [FK_ModuleCreated_ToUser] FOREIGN KEY ([UserCreated]) REFERENCES [User]([UserId]),
  CONSTRAINT [FK_ModuleUpdated_ToUser] FOREIGN KEY ([UserUpdated]) REFERENCES [User]([UserId])
)
