CREATE TABLE [dbo].[Session]
(
  [SessionId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
  [UserId] UNIQUEIDENTIFIER NOT NULL, 
  [Created] DATETIME NOT NULL
  CONSTRAINT [FK_Session_ToUser] FOREIGN KEY ([UserId]) REFERENCES [User]([UserId])
)
