CREATE TABLE [dbo].[User]
(
  [UserId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY , 
  [FullName] VARCHAR(150) NOT NULL, 
  [Email] VARCHAR(150) NOT NULL UNIQUE, 
  [ProfileId] UNIQUEIDENTIFIER NOT NULL,
  [Created] DATETIME NOT NULL , 
  [Updated] DATETIME NOT NULL, 
  [UserCreated] UNIQUEIDENTIFIER NULL, 
  [UserUpdated] UNIQUEIDENTIFIER NULL, 
  [IsActive] BIT NOT NULL DEFAULT 1, 
  CONSTRAINT [FK_User_ToProfile] FOREIGN KEY ([ProfileId]) REFERENCES [Profile]([ProfileId])
)
