CREATE TABLE [dbo].[User]
(
  [UserId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY , 
  [Mail] VARCHAR(100) NOT NULL, 
  [FullName] VARCHAR(100) NOT NULL, 
  [UserName] VARCHAR(100) NOT NULL, 
  [ProfileId] UNIQUEIDENTIFIER NOT NULL,
  [Created] DATETIME NOT NULL , 
  [Updated] DATETIME NOT NULL, 
  [UserCreated] UNIQUEIDENTIFIER NULL, 
  [UserUpdated] UNIQUEIDENTIFIER NULL, 
  [IsActive] BIT NOT NULL DEFAULT 1, 
  [Password] VARCHAR(150) NOT NULL DEFAULT 'IAVEheclJpdrYHHfKsUOTgE9h+CSIw==',
  CONSTRAINT [FK_User_ToProfile] FOREIGN KEY ([ProfileId]) REFERENCES [Profile]([ProfileId])
)
